const SHOP_DATA = {
  masks: {
    id: 1,
    title: "Masks",
    routeName: "masks",
    items: [
      {
        id: 1,
        name: "Protection Mask",
        imageUrl: "/images/shop-img/masks/mask_1.jpg",
        price: 1,
      },
      {
        id: 2,
        name: "Reusable Cotton Mask Black",
        imageUrl: "/images/shop-img/masks/mask_9.jpg",
        price: 5,
      },
      {
        id: 3,
        name: "Reusable Cotton Mask Floral",
        imageUrl: "/images/shop-img/masks/mask_3.jpg",
        price: 7,
      },
      {
        id: 4,
        name: "FFP2 Mask",
        imageUrl: "/images/shop-img/masks/mask_4.jpg",
        price: 3,
      },
      {
        id: 5,
        name: "Reusable Cotton Mask Kids",
        imageUrl: "/images/shop-img/masks/mask_5.jpg",
        price: 5,
      },
      {
        id: 6,
        name: "FFP3 Mask",
        imageUrl: "/images/shop-img/masks/mask_8.jpg",
        price: 10,
      },
      {
        id: 7,
        name: "FFP2 Masks 20pieces",
        imageUrl: "/images/shop-img/masks/mask_7.jpg",
        price: 40,
      },
      {
        id: 8,
        name: "Disposable Masks 50pieces",
        imageUrl: "/images/shop-img/masks/mask_6.jpg",
        price: 30,
      },
    ],
  },
  sanitize: {
    id: 2,
    title: "Hand Sanitizers",
    routeName: "hand sanitizers",
    items: [
      {
        id: 10,
        name: "Dettol Touch 200ml",
        imageUrl: "/images/shop-img/sanitizers/sanitizer_1.jpg",
        price: 10,
      },
      {
        id: 11,
        name: "MedexLabs Hand Sanitizer 50ml",
        imageUrl: "/images/shop-img/sanitizers/sanitizer_10.jpg",
        price: 3,
      },
      {
        id: 12,
        name: "Zidac Hand Gel 500ml",
        imageUrl: "/images/shop-img/sanitizers/sanitizer_3.jpg",
        price: 35,
      },
      {
        id: 13,
        name: "Purell Hand Sanitizer 236ml",
        imageUrl: "/images/shop-img/sanitizers/sanitizer_14.jpg",
        price: 10,
      },
      {
        id: 14,
        name: "Purell Hand Sanitizer 2L",
        imageUrl: "/images/shop-img/sanitizers/sanitizer_5.jpg",
        price: 88,
      },
      {
        id: 15,
        name: "Germ-X Hand Sanitizer 1L",
        imageUrl: "/images/shop-img/sanitizers/sanitizer_6.jpg",
        price: 40,
      },
      {
        id: 16,
        name: "Kroger Hand Sanitizer 946ml",
        imageUrl: "/images/shop-img/sanitizers/sanitizer_7.jpg",
        price: 40,
      },
      {
        id: 17,
        name: "Zelcos Hand Sanitizer 5L",
        imageUrl: "/images/shop-img/sanitizers/sanitizer_8.jpg",
        price: 150,
      },
    ],
  },
  cproducts: {
    id: 3,
    title: "Cleaning Products",
    routeName: "cleaning products",
    items: [
      {
        id: 18,
        name: "Igienol 1L",
        imageUrl: "/images/shop-img/cproducts/cp_1.jpg",
        price: 5,
      },
      {
        id: 19,
        name: "Igienol Spray 750ml",
        imageUrl: "/images/shop-img/cproducts/cp_2.jpg",
        price: 5,
      },
      {
        id: 20,
        name: "Sanytol 1L",
        imageUrl: "/images/shop-img/cproducts/cp_3.jpg",
        price: 6,
      },
      {
        id: 21,
        name: "Sanytol Spray 750ml",
        imageUrl: "/images/shop-img/cproducts/cp_4.jpg",
        price: 4,
      },
      {
        id: 22,
        name: "Dettol Laundry Cleanser 1.5L",
        imageUrl: "/images/shop-img/cproducts/cp_5.jpg",
        price: 8,
      },
      {
        id: 23,
        name: "Dettol Spray 750ml",
        imageUrl: "/images/shop-img/cproducts/cp_6.jpg",
        price: 5,
      },
      {
        id: 24,
        name: "Dettol Anti-Bacterial Wipes 15pieces",
        imageUrl: "/images/shop-img/cproducts/cp_7.jpg",
        price: 3,
      },
      {
        id: 25,
        name: "Doctor Wipe's Anti-Bacterial Wipes 72pieces",
        imageUrl: "/images/shop-img/cproducts/cp_8.jpg",
        price: 7,
      },
    ],
  },
  covid19: {
    id: 4,
    title: "COVID-19 Packages",
    routeName: "covid-19 packages",
    items: [
      {
        id: 26,
        name: "5 X Protection Mask",
        imageUrl: "/images/shop-img/masks/mask_1.jpg",
        price: 3,
      },
      {
        id: 27,
        name: "3 X Reusable Cotton Mask Black",
        imageUrl: "/images/shop-img/masks/mask_9.jpg",
        price: 13,
      },
      {
        id: 28,
        name: "2 X Dettol Touch 200ml",
        imageUrl: "/images/shop-img/sanitizers/sanitizer_1.jpg",
        price: 15,
      },
      {
        id: 29,
        name: "2 X Purell Hand Sanitizer 236ml",
        imageUrl: "/images/shop-img/sanitizers/sanitizer_14.jpg",
        price: 15,
      },
      {
        id: 30,
        name: "2 X Dettol Anti-Bacterial Wipes 15pieces",
        imageUrl: "/images/shop-img/cproducts/cp_7.jpg",
        price: 5,
      },
      {
        id: 31,
        name: "3 X Heinz Baked Beanz",
        imageUrl: "/images/shop-img/food/food_1.jpg",
        price: 5,
      },
      {
        id: 32,
        name: "2 X Keystone Chicken",
        imageUrl: "/images/shop-img/food/food_5.jpg",
        price: 14,
      },
    ],
  },
  food: {
    id: 5,
    title: "Canned Food",
    routeName: "canned food",
    items: [
      {
        id: 33,
        name: "Heinz Baked Beanz",
        imageUrl: "/images/shop-img/food/food_1.jpg",
        price: 2,
      },
      {
        id: 34,
        name: "Heinz Sweet Corn",
        imageUrl: "/images/shop-img/food/food_2.jpg",
        price: 2,
      },
      {
        id: 35,
        name: "Heinz Green Peas",
        imageUrl: "/images/shop-img/food/food_3.jpg",
        price: 1,
      },
      {
        id: 36,
        name: "Heinz Chopped Tomatoes",
        imageUrl: "/images/shop-img/food/food_4.jpg",
        price: 1,
      },
      {
        id: 37,
        name: "Keystone Chicken",
        imageUrl: "/images/shop-img/food/food_5.jpg",
        price: 8,
      },
      {
        id: 38,
        name: "Keystone Ground Beef",
        imageUrl: "/images/shop-img/food/food_6.jpg",
        price: 8,
      },
      {
        id: 39,
        name: "D'aucy chili mix",
        imageUrl: "/images/shop-img/food/food_10.jpg",
        price: 2,
      },
      {
        id: 40,
        name: "D'aucy Mexican Stir",
        imageUrl: "/images/shop-img/food/food_9.jpg",
        price: 2,
      },
    ],
  },
};

export default SHOP_DATA;
